### ISSUE TITLE
bin/rails webpacker:compileができない

### ISSUE THREAD

**Issue by moegi29** [motohiro-mm/Perfect_Ruby_on_Rails_Ch4#1]
## エラー内容
10/5のパRails輪読会
P.174 4章4-1-2 Webpackerの基本的な動作の"Webpackerで扱うエントリーポイント"を読んでいたところ 
`bin/rails webpacker:compile`をしようとしたけどエラーが出てビルドできなかった😿

実行環境：WSL2 Ubuntu20.04
### エラーログ
```
$ bin/rails webpacker:compile
Could not find sqlite3-1.6.6 in any of the sources
Run `bundle install` to install missing gems.
```

**Comment by moegi29** [comment]
## bundle install をしてみたけどエラー
`$ bin/rails webpacker:compile`で出力されたメッセージ通りに`bundle install`をしてみると`An error occurred while installing sqlite3 (1.6.6), and Bundler cannot continue.`とエラーログが出力されsqlite3 (1.6.6) のインストール中にエラーが発生し、Bundler を続行できない。
### エラーログ
```
$ bundle install
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 13.0.6
Using concurrent-ruby 1.2.2
Using marcel 1.0.2
Using thread_safe 0.3.6
Using zeitwerk 2.6.12
Using builder 3.2.4
:
Using railties 6.0.6.1
Using activestorage 6.0.6.1
Using webpacker 5.4.4
Using actionmailbox 6.0.6.1
Using actiontext 6.0.6.1
Using sassc-rails 2.1.2
Using rails 6.0.6.1
Using web-console 4.2.1
Using sass-rails 6.0.0
Installing sqlite3 1.6.6 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/mm/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/sqlite3-1.6.6/ext/sqlite3
/home/mm/.rbenv/versions/2.7.8/bin/ruby -I /home/mm/.rbenv/versions/2.7.8/lib/ruby/2.7.0 -r ./siteconf20231005-55496-1cpbele.rb extconf.rb
Building sqlite3-ruby using packaged sqlite3.
Extracting sqlite-autoconf-3430100.tar.gz into tmp/x86_64-linux-gnu/ports/sqlite3/3.43.1... OK
Running 'configure' for sqlite3 3.43.1... OK
Running 'compile' for sqlite3 3.43.1... OK
Running 'install' for sqlite3 3.43.1... OK
Activating sqlite3 3.43.1 (from /home/kmz/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/sqlite3-1.6.6/ports/x86_64-linux-gnu/sqlite3/3.43.1)...

Could not configure the build properly (pkg_config). Please install either the `pkg-config` utility or the `pkg-config` rubygem.

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/home/kmz/.rbenv/versions/2.7.8/bin/$(RUBY_BASE_NAME)
        --help
        --download-dependencies
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlcipher-dir
        --without-sqlcipher-dir
        --with-sqlcipher-include
        --without-sqlcipher-include
        --with-sqlcipher-lib
        --without-sqlcipher-lib
        --enable-system-libraries
        --disable-system-libraries
        --with-sqlcipher
        --without-sqlcipher
        --with-sqlcipher-dir
        --without-sqlcipher-dir
        --with-sqlcipher-include
        --without-sqlcipher-include
        --with-sqlcipher-lib
        --without-sqlcipher-lib
        --with-sqlite-source-dir
        --with-sqlite-cflags
        --without-sqlite-cflags
        --with-/home/mm/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/sqlite3-1.6.6/ports/x86_64-linux-gnu/sqlite3/3.43.1/lib/pkgconfig/sqlite3.pc-config
        --without-/home/mm/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/sqlite3-1.6.6/ports/x86_64-linux-gnu/sqlite3/3.43.1/lib/pkgconfig/sqlite3.pc-config
        --with-pkg-config
        --without-pkg-config

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/mm/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/sqlite3-1.6.6/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/kmz/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/gems/sqlite3-1.6.6 for inspection.
Results logged to /home/mm/.rbenv/versions/2.7.8/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/sqlite3-1.6.6/gem_make.out

  /home/kmz/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
  /home/kmz/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  /home/kmz/.rbenv/versions/2.7.8/lib/ruby/2.7.0/tempfile.rb:291:in `open'
  /home/kmz/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
  /home/kmz/.rbenv/versions/2.7.8/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in build_extension'
:
create_threads'
:
**An error occurred while installing sqlite3 (1.6.6), and Bundler cannot continue.**

In Gemfile:
  sqlite3
```

**Comment by moegi29** [comment]
## bin/rails webpacker:compile するために試行錯誤中
### ① sqlite3をインストール
```
gem install sqlite3 -v '1.6.6'
```
sqlite3のインストールは成功
![image](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/63eb81b6-0c7e-449c-9c03-5773a4576945)
### ➁ Gemfile.lockを削除
プロジェクトディレクトリ内のGemfile.lockファイルを一度削除する。
```
rm Gemfile.lock
```
### ③ Bundlerのキャッシュをクリア
```
bundle clean --force
```
![image](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/0491570c-53ae-493c-bebe-c51d02c0b0b7)
### ④ Bundlerをアップデート
```
gem update bundler
```
### ⑤ bundle install する
```
bundle install
```
![image](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/502150e0-9851-48f3-a0cf-6bb687ecd1d4)
### ⑥ Webpackerコンパイルを再試行
```
bin/rails webpacker:compile
```
エラーメッセージは変わった！
![image](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/a6ac7920-0901-44f2-a44e-5342be3af811)
↓
`bin/rails webpacker:compile`は動くようになったけどコンパイル中に新たなエラーが出ている。
`error:0308010C:digital envelope routines::unsupported`と出ているのでSSL関連の問題、、、？🤔
![image](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/9b5039de-8a77-4b89-9f2e-09641e3b9a7c)

<details><summary>再作成されたGemfile.lock</summary><div>

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (6.0.6.1)
      actionpack (= 6.0.6.1)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
    actionmailbox (6.0.6.1)
      actionpack (= 6.0.6.1)
      activejob (= 6.0.6.1)
      activerecord (= 6.0.6.1)
      activestorage (= 6.0.6.1)
      activesupport (= 6.0.6.1)
      mail (>= 2.7.1)
    actionmailer (6.0.6.1)
      actionpack (= 6.0.6.1)
      actionview (= 6.0.6.1)
      activejob (= 6.0.6.1)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (6.0.6.1)
      actionview (= 6.0.6.1)
      activesupport (= 6.0.6.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actiontext (6.0.6.1)
      actionpack (= 6.0.6.1)
      activerecord (= 6.0.6.1)
      activestorage (= 6.0.6.1)
      activesupport (= 6.0.6.1)
      nokogiri (>= 1.8.5)
    actionview (6.0.6.1)
      activesupport (= 6.0.6.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activejob (6.0.6.1)
      activesupport (= 6.0.6.1)
      globalid (>= 0.3.6)
    activemodel (6.0.6.1)
      activesupport (= 6.0.6.1)
    activerecord (6.0.6.1)
      activemodel (= 6.0.6.1)
      activesupport (= 6.0.6.1)
    activestorage (6.0.6.1)
      actionpack (= 6.0.6.1)
      activejob (= 6.0.6.1)
      activerecord (= 6.0.6.1)
      marcel (~> 1.0)
    activesupport (6.0.6.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    bindex (0.8.1)
    bootsnap (1.16.0)
      msgpack (~> 1.2)
    builder (3.2.4)
    byebug (11.1.3)
    capybara (3.39.2)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.2.2)
    crass (1.0.6)
    date (3.3.3)
    erubi (1.12.0)
    ffi (1.16.3)
    globalid (1.1.0)
      activesupport (>= 5.0)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    jbuilder (2.11.5)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    loofah (2.21.3)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.2)
    matrix (0.4.2)
    method_source (1.0.0)
    mini_mime (1.1.5)
    minitest (5.20.0)
    msgpack (1.7.2)
    net-imap (0.4.0)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.1)
      timeout
    net-smtp (0.4.0)
      net-protocol
    nio4r (2.5.9)
    nokogiri (1.15.4-x86_64-linux)
      racc (~> 1.4)
    public_suffix (5.0.3)
    puma (4.3.12)
      nio4r (~> 2.0)
    racc (1.7.1)
    rack (2.2.8)
    rack-proxy (0.7.7)
      rack
    rack-test (2.1.0)
      rack (>= 1.3)
    rails (6.0.6.1)
      actioncable (= 6.0.6.1)
      actionmailbox (= 6.0.6.1)
      actionmailer (= 6.0.6.1)
      actionpack (= 6.0.6.1)
      actiontext (= 6.0.6.1)
      actionview (= 6.0.6.1)
      activejob (= 6.0.6.1)
      activemodel (= 6.0.6.1)
      activerecord (= 6.0.6.1)
      activestorage (= 6.0.6.1)
      activesupport (= 6.0.6.1)
      bundler (>= 1.3.0)
      railties (= 6.0.6.1)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (6.0.6.1)
      actionpack (= 6.0.6.1)
      activesupport (= 6.0.6.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rake (13.0.6)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    regexp_parser (2.8.1)
    rexml (3.2.6)
    rubyzip (2.3.2)
    sass-rails (6.0.0)
      sassc-rails (~> 2.1, >= 2.1.1)
    sassc (2.4.0)
      ffi (~> 1.9)
    sassc-rails (2.1.2)
      railties (>= 4.0.0)
      sassc (>= 2.0)
      sprockets (> 3.0)
      sprockets-rails
      tilt
    selenium-webdriver (4.9.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    semantic_range (3.0.0)
    spring (2.1.1)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.4.2)
      actionpack (>= 5.2)
      activesupport (>= 5.2)
      sprockets (>= 3.0.0)
    sqlite3 (1.6.6-x86_64-linux)
    thor (1.2.2)
    thread_safe (0.3.6)
    tilt (2.3.0)
    timeout (0.4.0)
    turbolinks (5.2.1)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.11)
      thread_safe (~> 0.1)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.3.1)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0, < 4.11)
    webpacker (5.4.4)
      activesupport (>= 5.2)
      rack-proxy (>= 0.6.1)
      railties (>= 5.2)
      semantic_range (>= 2.3.0)
    websocket (1.2.10)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.12)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  bootsnap (>= 1.4.2)
  byebug
  capybara (>= 2.15)
  jbuilder (~> 2.7)
  listen (~> 3.2)
  puma (~> 4.1)
  rails (~> 6.0.6, >= 6.0.6.1)
  sass-rails (>= 6)
  selenium-webdriver
  spring
  spring-watcher-listen (~> 2.0.0)
  sqlite3 (~> 1.6.6)
  turbolinks (~> 5)
  tzinfo-data
  web-console (>= 3.3.0)
  webdrivers
  webpacker (~> 5.0)

RUBY VERSION
   ruby 2.7.8p225

BUNDLED WITH
   2.4.20

```　
</div></details>

**Comment by motohiro-mm** [comment]
同じエラーか分からないのですが、nodeのバージョンが最新すぎると`error:0308010C:digital envelope routines::unsupported`が起こるという記事をいくつか見つけたので、どうでしょうか？

https://zenn.dev/pontagon333/articles/26c89cbc14e81f
https://qiita.com/akitkat/items/f455bbc088a408cbc3a5
https://qiita.com/yuzu_283879391/items/8e9acaea257d64231037

**Comment by motohiro-mm** [comment]
話が前後してすみません。

最初のエラーですが、元のGemfile.lockと上記のGemfile.lockを比較したところ何ヶ所か違いがありました。
1番の大きな違いは、218行目の`PLATFORM`が元は`darwin`で、上記は`linux`になっている点です。
`x86_64-darwin-22`→`x86_64-linux`

参考サイトより引用です。https://autovice.jp/articles/150
>例えば、RailsアプリをmacOSで作成すると、Bundlerが実行できるプラットフォームはmacOSのみとなっているため、そのままではLinuxなどの別のOSでBundlerを実行することができません。
Bundler 2.1.x以前はBundlerが実行できるプラットフォームにrubyとだけ記述されていたので、macOSで作成したRailsアプリでも何もしなくてもLinuxへデプロイできていました。
Bundler 2.2.xからは開発者がBundlerを実行する適切なプラットフォームを追加する必要があります。

私はMacで`rails new`したので、Macの方は動作しそれ以外の方はうまくいかなかったのかなと推測します。
一度Gemlfile.lockを削除し再度`bundle install`することで自身の環境のPLATFORMに変わったんだと思いました。
つまり作成者の私がやっておかなければいけなかったことですね。すみません。

sqlite3も以下のように変化していたので同じ影響かと思います。
`sqlite3 (1.6.6-x86_64-darwin)`→`sqlite3 (1.6.6-x86_64-linux)`

ちなみにCh2,Ch3ではPLATFORMは`ruby`となっていたので、全員問題なく動作できたのだと思いました。

**Comment by moegi29** [comment]
元のGemfile.lockと新しいGemfile.lock比較してくださりありがとうございました🙏
Macで`rails new`した場合Bundlerが実行できるのはmacOSのみとなるのですね！知らなかったです～！
調べてくださりありがとうございます。

一個前にコメント頂いた内容なのですが、nodeのバージョンを安定版にしてみたのですが変わらずでした。
一応やってみたことをメモしておきます😺

**Comment by moegi29** [comment]
## Error: error:0308010C:digital envelope routines::unsupported エラーでやったこと
### エラー内容
`bin/rails webpacker:compile`をすると`Error: error:0308010C:digital envelope routines::unsupported`が出てしまいコンパイルができない。
![image](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/fa0b669a-3846-47a5-9efa-c7eee3047cde)
##
### 1. nodeのバージョン確認
```
$ node -v
v20.5.1
```
### 2. nodeのバージョンを安定版にしてみる
```
$ nvm install --lts
Installing latest LTS version.
v18.18.0 is already installed.
Now using node v18.18.0 (npm v9.8.1)
```
### 3. nodeのバージョン確認
```
$ node -v
v18.18.0
```
### 4. bin/rails webpacker:compileを試す
WebpackerがYarnのバージョンを1以上4未満と要求しているが、実行環境ではバージョン0.32+gitがインストールされているために発生している。
![スクリーンショット 2023-10-06 003422](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/692971b8-d663-4282-b22a-a3170232f8bf)

### 5. 最新のYarnをダウンロード
```
npm install -g yarn
```
### 6. Yarnのバージョン確認
```
yarn --version
1.22.19
```
### 7. 再度bin/rails webpacker:compileを試す
![image](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/fa0b669a-3846-47a5-9efa-c7eee3047cde)
うーん、変わらず～😿😿

**Comment by moegi29** [comment]
## Error: error:0308010C:digital envelope routines::unsupported エラーでやったこと 2
- bin/rails webpacker:clean webpacker:clobber で webpacker の生成物を消してみる
- node_modules をまるごと消して NPM パッケージを再インストールしてみる
- ブランチごと消して再度クローンし`bin/rails webpacker:compile`してもコンパイルはできませんでした。

**Comment by moegi29** [comment]
## 原因 bin/webpack内に追記すべき環境変数が無かった
motohiroさんが追記してくれたNode.js v18 で問題を回避するためのコード`ENV["NODE_OPTIONS"] = "--openssl-legacy-provider"`が私の環境での`bin/webpack内`に無かったことが原因でした🙇🙇🙇

![スクリーンショット 2023-10-07 180140](https://github.com/motohiro-mm/Perfect_Ruby_on_Rails_Ch4/assets/111144394/40969f79-26f3-4981-bef5-081f4962f2a9)

環境変数を追記したらコンパイルできました～！！！✨

**Comment by moegi29** [comment]
## 解決方法
- nove v16以下に下げる
- node v18の場合は`bin/webpack内`に環境変数`ENV["NODE_OPTIONS"] = "--openssl-legacy-provider"`を追記する
